# MVP Semester Configuration
# Minimal configuration for MVP testing and development

# Configuration metadata
version: "1.0"
schema_version: 1

# Semester information
semester:
  code: "MVP_2024"
  name: "MVP 2024"
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  description: "MVP semester for Insurance Manager development and testing"

# Base configuration to inherit from
base_configuration:
  name: "default"
  version: 1

# Game parameter overrides (simplified for MVP)
game_parameters:
  # Economic parameters
  economic:
    base_demand_multiplier: 1.0
    price_elasticity:
      auto: -1.2
      home: -0.8
    market_growth_rate: 0.03
    inflation_rate: 0.02
    
  # Turn timing parameters  
  turn:
    turn_duration_days: 7
    decision_deadline: "Sunday 23:59:59 EST"
    processing_start: "Monday 00:00:00 EST"
    late_submission_penalty: 0.05
    
  # Initial values for new companies
  initial_values:
    starting_capital: 5000000
    home_state_discount: 0.5
    initial_solvency_ratio: 3.0
    
  # CEO system parameters (simplified)
  ceo_parameters:
    starting_age_range:
      min: 35
      max: 40
    attribute_ranges:
      leadership:
        min: 20
        max: 40
      risk_intelligence:
        min: 20
        max: 40
      market_acumen:
        min: 20
        max: 40
      regulatory_mastery:
        min: 20
        max: 40
      innovation_capacity:
        min: 20
        max: 40
      deal_making:
        min: 20
        max: 40
      financial_expertise:
        min: 20
        max: 40
      crisis_command:
        min: 20
        max: 40
    progression:
      profit_per_skill_point: 10000000
      retirement_age: 65
    
  # Product tiers (simplified)
  product:
    tiers:
      basic:
        price_modifier: 0.8
        risk_selection: 1.3
      standard:
        price_modifier: 1.0
        risk_selection: 1.0
      premium:
        price_modifier: 1.3
        risk_selection: 0.9
    switching_cost: 100000

# Plugin configuration (minimal for MVP)
plugins:
  CEOSystemPlugin:
    enabled: true
    config:
      enable_progression: true
      enable_retirement: false
      enable_special_bonuses: false
    
  MarketEventsPlugin:
    enabled: true
    config:
      event_probability: 0.05
      event_types:
        - boom
        - recession
      severity_range: [0.8, 1.2]
      
  InvestmentManagerPlugin:
    enabled: true
    config:
      rebalance_frequency: "monthly"
      skill_impact_multiplier: 1.0
      
  RegulatoryCompliancePlugin:
    enabled: true
    config:
      audit_base_probability: 0.05
      compliance_check_frequency: "quarterly"

# Feature flags for MVP (minimal features)
feature_flags:
  - name: "plugin.CEOSystemPlugin"
    enabled: true
    scope: "semester"
    
  - name: "plugin.MarketEventsPlugin"
    enabled: true
    scope: "semester"
    
  - name: "plugin.InvestmentManagerPlugin"
    enabled: true
    scope: "semester"
    
  - name: "plugin.RegulatoryCompliancePlugin"
    enabled: true
    scope: "semester"
    
  # Advanced features disabled for MVP
  - name: "advanced_reporting"
    enabled: false
    scope: "semester"
    
  - name: "custom_products"
    enabled: false
    scope: "semester"
    
  - name: "middle_management"
    enabled: false
    scope: "semester"

# Custom rules for MVP (minimal)
custom_rules:
  special_modifiers:
    mvp_testing_bonus:
      description: "Development testing bonus"
      value: 0.0
      condition: "always"
      
  constraints:
    max_companies_per_user: 3
    allow_company_reset: true
    enable_practice_mode: true

# Development settings for MVP
development:
  fast_forward_enabled: true
  debug_mode: true
  bypass_deadlines: true
  show_hidden_metrics: true